## NAME - PARIKSHIT SAHU
## COGNIFYZ TECHNOLOGIES
### MACHINE LEARNING TASK 1
#### Objective: Build a machine learning model to predict the aggregate rating of a restaurant based on other featuress

#### LOADING THE LIBRARIES

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

### LOADING THE DATASET

In [3]:
data = pd.read_csv('D:\CERTIFICATES\Dataset_cognifyz.csv')

In [4]:
data

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

### PRINTING THE INFO , DESCRIPTION AND SHAPE OF THE DATA

In [5]:
data.shape

(9551, 21)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [9]:
data.describe()

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

### CHECKING FOR NULL VALUES IN THE DATASET

In [11]:
data.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

### SPLITTING THE DATASET INTO INDEPENDENT AND DEPENDANT VARIABLES
### X IS THE INDEPENDANT AND Y IS THE DEPENDANT VARIABLE

In [14]:
x = data.drop('Aggregate rating', axis=1)

In [15]:
x

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,80,Turkish Lira(TL),No,No,No,No,3,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",105,Turkish Lira(TL),No,No,No,No,3,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",170,Turkish Lira(TL),No,No,No,No,4,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,120,Turkish Lira(TL),No,No,No,No,4,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,55,Turkish Lira(TL),No,No,No,No,2,Green,Very Good,591

In [16]:
y = data['Aggregate rating']

In [17]:
y

0       4.8
1       4.5
2       4.4
3       4.9
4       4.8
       ...
9546    4.1
9547    4.2
9548    3.7
9549    4.0
9550    4.0
Name: Aggregate rating, Length: 9551, dtype: float64

### SPLITTING THE DATASET FOR TRAINING AND TESTING PURPOSE

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 40)

In [19]:
x_train

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Rating color,Rating text,Votes
8432,594,Cafe Coffee Day,1,Noida,"G-54, Sector 18, Noida",Sector 18,"Sector 18, Noida",77.323980,28.569665,Cafe,450,Indian Rupees(Rs.),No,Yes,No,No,1,Yellow,Good,125
6360,8600,4th Street Cafe,1,New Delhi,"14, G Block, DDA Market, Preet Vihar, New Delhi",Preet Vihar,"Preet Vihar, New Delhi",77.297921,28.642275,Fast Food,500,Indian Rupees(Rs.),No,Yes,No,No,2,Yellow,Good,145
6900,309874,The Upper Crust,1,New Delhi,"Shop 4, Upper Ground Floor, Plot 4, Khasra 132...",Saket,"Saket, New Delhi",77.212343,28.519141,"Pizza, Fast Food",550,Indian Rupees(Rs.),No,No,No,No,2,Orange,Average,15
6146,308845,Aggarwal Sweets,1,New Delhi,"A 15, Ganesh Nagar Complex, Pandav Nagar, New ...",Pandav Nagar,"Pandav Nagar, New Delhi",77.285380,28.619105,Street Food,250,Indian Rupees(Rs.),No,No,No,No,1,Orange,Average,5
7015,300185,High On Burgers,1,New Delhi,"57, Opposite Venkateshwara College, Satyaniket...",Satyaniketan,"Satyaniketan, New Delhi",77.169141,28.587529,"Fast Food, Burger",300,Indian Rupees(Rs.),No,Yes,No,No,1,Yellow,Good,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7839,300941,Hari Om Bhojanalaya,1,New Delhi,"H-149, Old Gupta Colony, Opposite Kalyan Vihar...",Vijay Nagar,"Vijay Nagar, New Delhi",77.197804,28.692129,North Indian,300,Indian Rupees(Rs.),No,No,No,No,1,Orange,Average,43
3603,18359292,Foodies,1,New Delhi,"Fun City Mall, Prashant Vihar, New Delhi","Fun City Mall, Prashant Vihar","Fun City Mall, Prashant Vihar, New Delhi",77.135978,28.712433,Italian,300,Indian Rupees(Rs.),No,No,No,No,1,White,Not rated,0
5959,18432628,Aloo Bhaji Restaurant,1,New Delhi,"C-19, DDA Sheds, Okhla Phase 1, New Delhi",Okhla Phase 1,"Okhla Phase 1, New Delhi",0.000000,0.000000,North Indian,500,Indian Rupees(Rs.),No,No,No,No,2,White,Not rated,0
5426,18489808,Swadist Bhojnalaya,1,New Delhi,"Shop 240, Ghitorni Village, MG Road, New Delhi",MG Road,"MG Road, New Delhi",77.145774,28.494662,"Chinese, North Indian",200,Indian Rupees(Rs.),No,No,No,No,1,White,Not rated,2
7608,310286,Today Pizza,1,New Delhi,"E-1, Khyala Road, Vishnu Garden, Tilak Nagar, ...",Tilak Nagar,"Tilak Nagar, New Delhi",77.103168,28.649055,Fast Food,250,Indian Rupees(Rs.),No,No,No,No,1,White,Not rated,3

In [20]:
y_train

8432    3.6
6360    3.5
6900    3.0
6146    2.9
7015    3.5
       ...
7839    3.4
3603    0.0
5959    0.0
5426    0.0
7608    0.0
Name: Aggregate rating, Length: 7640, dtype: float64

In [21]:
x_test

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Rating color,Rating text,Votes
5092,18313112,Taste of India,1,New Delhi,"A-53, NH-8, Near IGI Airport, Mahipalpur, Ne...",Mahipalpur,"Mahipalpur, New Delhi",77.129371,28.550517,"North Indian, Mughlai, Chinese",1000,Indian Rupees(Rs.),Yes,No,No,No,3,White,Not rated,0
7150,18435311,Ex- Taj Foods,1,New Delhi,"Main Road, Maujpur, Shahdara, New Delhi",Shahdara,"Shahdara, New Delhi",77.271893,28.677039,North Indian,400,Indian Rupees(Rs.),No,No,No,No,1,White,Not rated,1
6332,18216703,Muncheezz,1,New Delhi,"G-4, Sarda Chamber 2, Plot 15, D Block, Prasha...",Prashant Vihar,"Prashant Vihar, New Delhi",77.137596,28.712410,Chinese,300,Indian Rupees(Rs.),No,No,No,No,1,White,Not rated,0
5260,18138441,Lahorian's Sweets & Bakers,1,New Delhi,"Shop 5, Plot 101, Gali 15, Pratap Nagar, Mayur...",Mayur Vihar Phase 1,"Mayur Vihar Phase 1, New Delhi",77.293569,28.604443,"Street Food, Desserts",250,Indian Rupees(Rs.),No,No,No,No,1,Orange,Average,5
3100,67,Fa Yian,1,New Delhi,"A-25/5, Middle Circle, Connaught Place, New Delhi",Connaught Place,"Connaught Place, New Delhi",77.217298,28.632811,Chinese,1200,Indian Rupees(Rs.),Yes,No,No,No,3,Green,Very Good,412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6219,310630,Firangi N More,1,New Delhi,"Shop 33, B-1 Market, Paschim Vihar, New Delhi",Paschim Vihar,"Paschim Vihar, New Delhi",77.108808,28.670108,"Chinese, Fast Food",400,Indian Rupees(Rs.),No,Yes,No,No,1,Red,Poor,43
2359,2300483,The Zaffran,1,Kanpur,"Ratan Zone, Coca-Cola Crossing, Ashok Nagar, K...",Ashok Nagar,"Ashok Nagar, Kanpur",80.313564,26.471617,"North Indian, Continental, Asian",800,Indian Rupees(Rs.),No,No,No,No,3,Orange,Average,51
2458,15717,The BrewMaster - The Mix Fine Dine,1,Ludhiana,"3rd Floor, Westend Mall, Rajguru Nagar, Ludhiana","Westend Mall, Rajguru Nagar","Westend Mall, Rajguru Nagar, Ludhiana",75.788259,30.885915,"North Indian, Continental",1500,Indian Rupees(Rs.),No,No,No,No,3,Yellow,Good,154
9007,18431190,Vyanjan,1,Noida,"Aditya Celebrity Homes Market, Sector 76, Near...",Sector 72,"Sector 72, Noida",77.383946,28.571271,North Indian,300,Indian Rupees(Rs.),No,No,No,No,1,White,Not rated,3
708,2500054,Angeethi Restaurant,1,Aurangabad,"Seven Hill Flyover, Jalna Road, Vidya Nagar, C...",CIDCO,"CIDCO, Aurangabad",75.353942,19.874733,"North Indian, Chinese",600,Indian Rupees(Rs.),No,No,No,No,2,Orange,Average,63

In [22]:
y_test

5092    0.0
7150    0.0
6332    0.0
5260    2.9
3100    4.0
       ...
6219    2.2
2359    3.3
2458    3.9
9007    0.0
708     3.3
Name: Aggregate rating, Length: 1911, dtype: float64

In [24]:
print(x_train.shape,
     y_train.shape,
     x_test.shape,
     y_test.shape)

(7640, 20) (7640,) (1911, 20) (1911,)

### PREPROCESSING THE DATASET

In [25]:
numeric_features = x.select_dtypes(include=['int64', 'float64']).columns
categorical_features = x.select_dtypes(include=['object']).columns

In [27]:
numeric_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='mean'))])

categorical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[('num', numeric_transformer, numeric_features),('cat', categorical_transformer, categorical_features)])

### DEFINING THE LINEAR REGRESSION MODEL

In [28]:
model = Pipeline(steps=[('preprocessor', preprocessor),('regressor', LinearRegression())])

### FITTING THE DATA INTO THE MODEL

In [29]:
model.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  Index(['Restaurant ID', 'Country Code', 'Longitude', 'Latitude',
       'Average Cost for two', 'Price range', 'Votes'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Cuisines', 'Currency', 'Has Table booking', 'Has Online delivery',
       'Is delivering now', 'Switch to order menu', 'Rating color',
       'Rating text'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

### PREDICTING THE OUTPUT

In [30]:
y_pred = model.predict(x_test)

In [55]:
y_pred_data = pd.DataFrame([y_pred])
y_pred_data

,0,1,2,3,4,5,6,7,8,9,...,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910
0,1.855398,1.846348,1.858632,1.866811,3.2548,1.850408,2.946053,1.866321,2.965697,4.141443,...,2.961333,8.159103,3.133045,2.969056,5.842308,2.955009,2.835972,3.063655,1.847515,2.845671

### EVALUATING THE ERROR IN THE MODEL

In [37]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [44]:
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 1.7538379929378314
R-squared: 0.2544545511959243

### INTERPRET THE MODEL RESULTS AND ANALYZE THE FEATURE IMPORTANCE

In [48]:
coefficients = model.named_steps['regressor'].coef_
intercept = model.named_steps['regressor'].intercept_

In [53]:
print("Coefficients:")
for feature, coef in zip(x_train.columns, coefficients):
    print(f"{feature}: {coef}")

print(f"Intercept: {intercept}")

Coefficients:
Restaurant ID: -5.937518613427728e-08
Restaurant Name: 0.00621564373436141
Country Code: -0.0026509748520868034
City: -1.1960581611708965e-05
Address: 3.1618192188780454e-06
Locality: 0.0001116572268494662
Locality Verbose: 0.000755682417360585
Longitude: 1.987967402762097e-08
Latitude: 5.147337314244314e-08
Cuisines: 4.858051983666469e-08
Average Cost for two: 4.0191101536965785e-08
Currency: 5.554867507414341e-08
Has Table booking: 3.7251420618050006e-08
Has Online delivery: 3.016497994087712e-08
Is delivering now: 1.8148990454436527e-08
Switch to order menu: -6.93866960144795e-08
Price range: 2.2620041443875827e-08
Rating color: -6.96797814118363e-08
Rating text: 1.9904518774515023e-08
Votes: -1.6001903802408845e-08
Intercept: 3.138180093510962